### ISSUE TITLE
1 validation error for DatasetMetadata

### ISSUE THREAD

**Issue by eric9n** [shapiromatron/bmds-archive#117] opened 2023-10-19 14:07 UTC
When running the code from the README documentation with pydantic version > 2, an error occurs.
Traceback (most recent call last):
  File "/Users/eric/3bms/test.py", line 4, in <module>
    dataset = bmds.DichotomousDataset(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/bmds/datasets/dichotomous.py", line 44, in __init__
    self.metadata = DatasetMetadata.parse_obj(metadata)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/typing_extensions.py", line 2360, in wrapper
    return arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1010, in parse_obj
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for DatasetMetadata

**Comment by shapiromatron** [comment] 2023-10-20 19:49
thanks! yes, I we've fixed in this on the `main` branch; since we [pin pydantic < 2](https://github.com/shapiromatron/bmds/blob/924a9d1df26ee23dc87eebf019971a174407b396/setup.cfg#L32). Can you confirm that the issue is resolved on the main branch?

**Comment by eric9n** [comment] 2023-10-21 00:43
I use "pip install bmds"

**Comment by shapiromatron** [comment] 2023-10-21 17:16
I just released a new version, [v23.3](https://pypi.org/project/bmds/23.3/). After updating, please let me know if this fixes this issue and we can close this issue. Thanks for reporting!

**Comment by eric9n** [comment] 2023-10-22 01:37
Yes, the issue with pydantic has been resolved. However, I encountered another problem: "symbol not found in flat namespace '__ZNKSt5ctypeIcE13_M_widen_initEv'". I'm wondering if the libDRBMD.dylib hasn't been adapted for Apple M1 Max. My platform is Apple M1 Max, macOS Sonoma (14.0), Python 3.11.5.

Here's the traceback of the error:

`Traceback (most recent call last):
  File "/Users/eric/3bms/test.py", line 17, in <module>
    session.execute()
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/bmds/bmds3/sessions.py", line 112, in execute
    model.execute_job()
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/bmds/bmds3/models/base.py", line 117, in execute_job
    self.execute()
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/bmds/bmds3/models/dichotomous.py", line 57, in execute
    dll = self.get_dll()
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/bmds/bmds3/models/base.py", line 102, in get_dll
    return BmdsLibraryManager.get_dll(bmds_version=cls.model_version, base_name="libDRBMD")
  File "/Users/eric/3bms/.venv/lib/python3.11/site-packages/bmds/bmds3/models/base.py", line 71, in get_dll
    dll = ctypes.cdll.LoadLibrary(str(path))
  File "/Users/eric/.asdf/installs/Python/3.11.5/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
  File "/Users/eric/.asdf/installs/Python/3.11.5/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/eric/3bms/.venv/lib/python3.11/site-packages/bmds/bin/BMDS330/libDRBMD.dylib, 0x0006): symbol not found in flat namespace '__ZNKSt5ctypeIcE13_M_widen_initEv'`

**Comment by shapiromatron** [comment] 2023-10-23 00:51
Thanks. This is an issue with the shared C++ version of the library, and shared objects, so far as I can tell. We're hoping a new version that we'll release in the next 6 months or so can hopefully fix this; we're in the process of rewriting the build system.

**Closed as completed** 2023-11-20 20:53 UTC
